### ISSUE TITLE
Allow skipping extraction step

### ISSUE THREAD

**Issue by alex-statsig** [reproducible-containers/buildkit-cache-dance#11]
The extraction step takes several minutes for large caches such as caching ~500MB of npm modules. If the actions/cache step had a cache hit, the extraction step is pointless (as the cache will not even be rewritten in that case anyway). This is actually fairly common since lockfiles dont change much. If this action could accept an input for "should-extract", this could be tied to the output of "cache-hit" from actions/cache, and save a few minutes on a lot of runs.

**Comment by kskalski** [comment]
Another use-case: only populate cache on certain workflow runs, e.g. skip it on PR / experimental branches.

**Comment by henryjw** [comment]
I've implemented a simple version of this feature. Feel free to clone my repo or reference the commit

Example here:
https://github.com/henryjw/pip-docker-cache-dance/commit/46661c021c2a8274d6cbd35455e9843d69db1287

Example run:
https://github.com/henryjw/pip-docker-cache-dance/actions/runs/7588164357/job/20670091003

**Comment by AkihiroSuda** [comment]
Thanks, merged #19 and released v2.1.4
